// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetFileList(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function HelloWorld():Promise<void>;

export function NowPath():Promise<string>;

export function ReadCover(arg1:string):Promise<Array<backend.ImageData>>;

export function Shutdown():Promise<void>;
