// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetBookCoverByBookinfo(arg1:backend.BookInfo):Promise<backend.BookImageData>;

export function GetBookInfoByKey(arg1:string):Promise<backend.BookInfo>;

export function GetBookListAll():Promise<Array<backend.BookInfo>>;

export function GetBookPageByBookinfo(arg1:backend.BookInfo,arg2:number):Promise<backend.BookImageData>;

export function GetBookPageThumbnailByBookinfo(arg1:backend.BookInfo,arg2:number):Promise<backend.BookImageData>;

export function GetBookPagesByBookinfo(arg1:backend.BookInfo,arg2:Array<number>):Promise<Array<backend.BookImageData>>;

export function GetBookinfoByAndConditions(arg1:{[key: string]: any}):Promise<backend.BookInfo>;

export function GetSeriesInfoByKey(arg1:string):Promise<backend.SeriesInfo>;

export function GetSeriesKeyListAll():Promise<Array<string>>;

export function GetSeriesListAll():Promise<Array<backend.SeriesInfo>>;

export function Greet(arg1:string):Promise<string>;

export function NowPath():Promise<string>;

export function SaveBookInfo(arg1:backend.BookInfo):Promise<void>;

export function ScanBookAll():Promise<void>;

export function ScraperInfo(arg1:string,arg2:string):Promise<backend.BookInfo>;

export function Shutdown():Promise<void>;

export function WriteComicInfo(arg1:backend.BookInfo):Promise<void>;

export function WriteComicInfoToZip(arg1:backend.BookInfo):Promise<void>;
