// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBookCoverByKey(arg1) {
  return window['go']['main']['App']['GetBookCoverByKey'](arg1);
}

export function GetBookInfoByKey(arg1) {
  return window['go']['main']['App']['GetBookInfoByKey'](arg1);
}

export function GetBookListAll() {
  return window['go']['main']['App']['GetBookListAll']();
}

export function GetBookPage(arg1, arg2) {
  return window['go']['main']['App']['GetBookPage'](arg1, arg2);
}

export function GetBookPageThumbnail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetBookPageThumbnail'](arg1, arg2, arg3, arg4);
}

export function GetBookPages(arg1, arg2) {
  return window['go']['main']['App']['GetBookPages'](arg1, arg2);
}

export function GetSeriesInfoByKey(arg1) {
  return window['go']['main']['App']['GetSeriesInfoByKey'](arg1);
}

export function GetSeriesKeyListAll() {
  return window['go']['main']['App']['GetSeriesKeyListAll']();
}

export function GetSeriesListAll() {
  return window['go']['main']['App']['GetSeriesListAll']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NowPath() {
  return window['go']['main']['App']['NowPath']();
}

export function ReadCover(arg1) {
  return window['go']['main']['App']['ReadCover'](arg1);
}

export function ScanBookAll() {
  return window['go']['main']['App']['ScanBookAll']();
}

export function ScraperInfo(arg1, arg2) {
  return window['go']['main']['App']['ScraperInfo'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function WriteComicInfo(arg1) {
  return window['go']['main']['App']['WriteComicInfo'](arg1);
}

export function WriteComicInfoToZip(arg1) {
  return window['go']['main']['App']['WriteComicInfoToZip'](arg1);
}
