// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBookCoverByBookinfo(arg1) {
  return window['go']['main']['App']['GetBookCoverByBookinfo'](arg1);
}

export function GetBookInfoByKey(arg1) {
  return window['go']['main']['App']['GetBookInfoByKey'](arg1);
}

export function GetBookListAll() {
  return window['go']['main']['App']['GetBookListAll']();
}

export function GetBookPageByBookinfo(arg1, arg2) {
  return window['go']['main']['App']['GetBookPageByBookinfo'](arg1, arg2);
}

export function GetBookPageThumbnailByBookinfo(arg1, arg2) {
  return window['go']['main']['App']['GetBookPageThumbnailByBookinfo'](arg1, arg2);
}

export function GetBookPagesByBookinfo(arg1, arg2) {
  return window['go']['main']['App']['GetBookPagesByBookinfo'](arg1, arg2);
}

export function GetBookinfoByAndConditions(arg1) {
  return window['go']['main']['App']['GetBookinfoByAndConditions'](arg1);
}

export function GetSeriesInfoByKey(arg1) {
  return window['go']['main']['App']['GetSeriesInfoByKey'](arg1);
}

export function GetSeriesKeyListAll() {
  return window['go']['main']['App']['GetSeriesKeyListAll']();
}

export function GetSeriesListAll() {
  return window['go']['main']['App']['GetSeriesListAll']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NowPath() {
  return window['go']['main']['App']['NowPath']();
}

export function ScanBookAll() {
  return window['go']['main']['App']['ScanBookAll']();
}

export function ScraperInfo(arg1, arg2) {
  return window['go']['main']['App']['ScraperInfo'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function WriteComicInfo(arg1) {
  return window['go']['main']['App']['WriteComicInfo'](arg1);
}

export function WriteComicInfoToZip(arg1) {
  return window['go']['main']['App']['WriteComicInfoToZip'](arg1);
}
