// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {utils} from '../models';

export function ExtractImagesFromZip(arg1:string,arg2:number):Promise<Array<main.ImageData>>;

export function ExtractImagesFromZipByPages(arg1:string,arg2:number):Promise<Array<main.ImageData>>;

export function FetchDirectoryTree(arg1:string):Promise<Array<utils.FileNode>>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetImageBytes(arg1:string):Promise<Array<number>>;

export function GetScraper(arg1:string,arg2:string):Promise<utils.BookInfo>;

export function GetThumbnails(arg1:string):Promise<Array<utils.ImageData>>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadComicInfoXML(arg1:string):Promise<main.ComicInfo>;

export function ReadZipInfo():Promise<void>;
